version: '3.8'

services:
  packinglist:
    build: .
    restart: unless-stopped
    container_name: packinglist
    env_file:
      - .env.local
    environment:
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=${GOOGLE_SERVICE_ACCOUNT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.packinglist.rule=Host(`packing.phloots.com`)"
      - "traefik.http.routers.packinglist.middlewares=protect-this-app@file"
